name: .NET Actions

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Install dependencies
      run: dotnet restore
    - name: Run tests
      run: dotnet test

  migrations:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Install dependencies
      run: dotnet restore
    - name: Setup EF Core
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update -s RestApi/ -p Infrastructure/ -c LotusDbContext
      env:
        ASPNETCORE_ENVIRONMENT: Production

  deploy:
    runs-on: ubuntu-latest
    needs: migrations
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        heroku_api: ${{ secrets.HEROKU_API_KEY }}
        heroku_app: ${{ secrets.HEROKU_APP_NAME }}

    steps:
    - uses: actions/checkout@v2
    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ matrix.heroku_api }}
      run: docker container:login
    - name: Build and push to Heroku
      env: 
        HEROKU_API_KEY: ${{ matrix:heroku_api }}
      run: heroku container:push -a ${{ matrix.heroku_app }} web
    - name: Deploy on Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_APP_NAME }} web
      run: heroku container:release -a ${{ matrix.heroku_app }} web 