name: .NET Actions

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore
    - name: Run tests
      run: dotnet test

  migrations:
    runs-on: ubuntu-latest
    needs: test
    #if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore
    - name: Setup EF Core
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update -s RestApi/ -p Infrastructure/ -c LotusDbContext
      env:
        ASPNETCORE_ENVIRONMENT: Production

  deploy:
    runs-on: ubuntu-latest
    needs: migrations
    #if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.7.8
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: master
      env:
        ASPNETCORE_ENVIROMENT: Production